server:
  port: 8081
spring:
  application:
    name: track_rejoice
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: false
    url: ${spring.datasource.url}
    password: ${${spring.datasource.password}
    user: ${spring.datasource.username}
    schemas: migrations
    locations: classpath:db/migration/postgresql
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 760121390009-sgn0o84bb0jo3q0hu4rult1fb3qnhfv1.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - email
#              - profile
hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE