server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  devtools:
    add-properties: false
  datasource:
      hikari:
        connection-timeout: 20000
        maximum-pool-size: 5
        max-lifetime: 1200000
        idle-timeout: 300000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  thymeleaf:
    cache: false
  application:
    name: track_rejoice
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: one.breece.track_rejoice.configuration.CustomPostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    url: ${spring.datasource.command.url}
    password: ${spring.datasource.command.password}
    user: ${spring.datasource.command.username}
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: emmanouil.psanis@gmail.com
    password: ldey bcqa eiip wdlm
    properties:
      mail:
        transport:
        protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
  main:
    allow-bean-definition-overriding: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 760121390009-sgn0o84bb0jo3q0hu4rult1fb3qnhfv1.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - email
#              - profile
support:
  email: emmanouil.psanis@gmail.com

#  tenant_identifier_resolver: one.breece.track_rejoice.configuration.TenantIdentifierResolver

aws:
  region: eu-west-3
  s3:
    bucket: trackrejoice-public-01

payments: enabled
