spring:
  flyway:
    locations: classpath:db/migration/postgresql, classpath:db/migration/dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
google:
  recaptcha:
    key:
      site: 6LePt94qAAAAAC835Gey8z39oANFjHs_rUzrX5gi
      secret: 6LePt94qAAAAALU1w7HqtqAtMu41i4LvEeOgDkXj
      threshold: 0.5
geocoding:
  key: 67bb5db6197e2623610027dpz0edd61
paypal:
  public: ARKXvgGgko6VP9WPaLba0QaaMGGu0WRDXOaw9qgt79YzRoBzH6NjyacWLzzRKZHpK61G8sjeWfwIne6u
  private: EB23fLmxFAJVNRiyQmr-obPK9nlEd39FnZ84jFsQDOjywFD6Bea5zjPs9ch3Kzl-iXcsFDtGiCcHM34-