server:
  port: 8081
spring:
  thymeleaf:
    cache: false
  application:
    name: track_rejoice
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    locations: classpath:db/migration/postgresql
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: emmanouil.psanis@gmail.com
    password: ldey bcqa eiip wdlm
    properties:
      mail:
        transport:
        protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
  main:
    allow-bean-definition-overriding: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 760121390009-sgn0o84bb0jo3q0hu4rult1fb3qnhfv1.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - email
#              - profile
support:
  email: USERNAME@gmail.com

hibernate:
  dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
#  tenant_identifier_resolver: one.breece.track_rejoice.configuration.TenantIdentifierResolver
logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
google:
  recaptcha:
    key:
      site: 6LePt94qAAAAAC835Gey8z39oANFjHs_rUzrX5gi
      secret: 6LePt94qAAAAALU1w7HqtqAtMu41i4LvEeOgDkXj
      threshold: 0.5
geocoding:
  key: 67bb5db6197e2623610027dpz0edd61
management:
  endpoints:
    web:
      exposure:
        include: httpexchanges
paypal:
  public: ARKXvgGgko6VP9WPaLba0QaaMGGu0WRDXOaw9qgt79YzRoBzH6NjyacWLzzRKZHpK61G8sjeWfwIne6u
  private: EB23fLmxFAJVNRiyQmr-obPK9nlEd39FnZ84jFsQDOjywFD6Bea5zjPs9ch3Kzl-iXcsFDtGiCcHM34-