server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  thymeleaf:
    cache: false
  application:
    name: track_rejoice
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: emmanouil.psanis@gmail.com
    password: ldey bcqa eiip wdlm
    properties:
      mail:
        transport:
        protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
  main:
    allow-bean-definition-overriding: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 760121390009-sgn0o84bb0jo3q0hu4rult1fb3qnhfv1.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - email
#              - profile
support:
  email: emmanouil.psanis@gmail.com

hibernate:
  dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
#  tenant_identifier_resolver: one.breece.track_rejoice.configuration.TenantIdentifierResolver

aws:
  region: eu-west-3
  s3:
    bucket: trackrejoice-image-qa

payments: enabled
