spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql, classpath:db/migration/dev
    password: ${spring.datasource.command.password}
    user: ${spring.datasource.command.username}
  datasource:
    command:
      url: jdbc:postgresql://localhost:5432/postgres
      username: root
      password: root
    query:
      url: jdbc:postgresql://localhost:5432/postgres
      username: root
      password: root
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
google:
  recaptcha:
    key:
      threshold: 0.5