CREATE SEQUENCE IF NOT EXISTS password_reset_token_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS verification_token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE all_points_bulletin
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number   VARCHAR(255),
    last_seen_date TIMESTAMP WITHOUT TIME ZONE,
    version        SMALLINT                                NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by     BIGINT,
    extra_info     VARCHAR(1024),
    enabled        BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_allpointsbulletin PRIMARY KEY (id)
);

CREATE TABLE app_user
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password                VARCHAR(255),
    username                VARCHAR(255)                            NOT NULL,
    first_name              VARCHAR(255),
    last_name               VARCHAR(255),
    account_non_expired     BOOLEAN                                 NOT NULL,
    account_non_locked      BOOLEAN                                 NOT NULL,
    credentials_non_expired BOOLEAN                                 NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    is_using2fa             BOOLEAN                                 NOT NULL,
    provider                VARCHAR(255),
    CONSTRAINT pk_appuser PRIMARY KEY (id)
);

CREATE TABLE means_of_transportation
(
    id                     BIGINT NOT NULL,
    last_seen_location     GEOMETRY(Point, 4326) NOT NULL,
    human_readable_address JSONB,
    CONSTRAINT pk_meansoftransportation PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id          BIGINT NOT NULL,
    token       VARCHAR(255),
    app_user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

CREATE TABLE pet
(
    id                     BIGINT NOT NULL,
    last_seen_location     GEOMETRY(Point, 4326) NOT NULL,
    human_readable_address JSONB,
    name                   VARCHAR(255),
    species                VARCHAR(255),
    breed                  VARCHAR(255),
    color                  VARCHAR(255),
    transponder_code       BIGINT,
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE trace
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version                SMALLINT                                NOT NULL,
    all_points_bulletin_id BIGINT                                  NOT NULL,
    location               GEOMETRY(Point, 4326)                   NOT NULL,
    date                   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_trace PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE verification_token
(
    id          BIGINT NOT NULL,
    token       VARCHAR(255),
    app_user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_verificationtoken PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_username UNIQUE (username);

ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_passwordresettoken_app_user UNIQUE (app_user_id);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verificationtoken_app_user UNIQUE (app_user_id);

ALTER TABLE means_of_transportation
    ADD CONSTRAINT FK_MEANSOFTRANSPORTATION_ON_ID FOREIGN KEY (id) REFERENCES all_points_bulletin (id);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_ID FOREIGN KEY (id) REFERENCES all_points_bulletin (id);

ALTER TABLE trace
    ADD CONSTRAINT FK_TRACE_ON_ALLPOINTSBULLETIN FOREIGN KEY (all_points_bulletin_id) REFERENCES all_points_bulletin (id);

ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFY_USER FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_VERIFY_USERywxdzN FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_app_user FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (id);