CREATE SEQUENCE IF NOT EXISTS password_reset_token_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS verification_token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE app_user
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password                VARCHAR(255),
    username                VARCHAR(255)                            NOT NULL,
    first_name              VARCHAR(255),
    last_name               VARCHAR(255),
    account_non_expired     BOOLEAN                                 NOT NULL,
    account_non_locked      BOOLEAN                                 NOT NULL,
    credentials_non_expired BOOLEAN                                 NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    is_using2fa             BOOLEAN                                 NOT NULL,
    provider                VARCHAR(255),
    CONSTRAINT pk_appuser PRIMARY KEY (id)
);

CREATE TABLE be_on_the_look_out
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number       VARCHAR(255),
    last_seen_date     TIMESTAMP WITHOUT TIME ZONE,
    last_seen_location GEOMETRY(Geometry, 4326)                NOT NULL,
    extra_info         VARCHAR(1024),
    sku                UUID                                    NOT NULL,
    state              VARCHAR(255),
    qr_code_key        VARCHAR(255),
    version            SMALLINT                                NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         BIGINT,
    CONSTRAINT pk_beonthelookout PRIMARY KEY (id)
);

CREATE TABLE bicycle
(
    id    BIGINT   NOT NULL,
    color VARCHAR(255),
    maker VARCHAR(255),
    model VARCHAR(255),
    year  SMALLINT NOT NULL,
    CONSTRAINT pk_bicycle PRIMARY KEY (id)
);

CREATE TABLE be_on_the_look_out_photo
(
    be_on_the_look_out_id BIGINT NOT NULL,
    bucket     VARCHAR(255),
    key        VARCHAR(255)
);

CREATE TABLE item
(
    id                BIGINT NOT NULL,
    short_description VARCHAR(255),
    color             VARCHAR(255),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id          BIGINT NOT NULL,
    token       VARCHAR(255),
    app_user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

CREATE TABLE pet
(
    id               BIGINT NOT NULL,
    name             VARCHAR(255),
    species          VARCHAR(255),
    breed            VARCHAR(255),
    sex              VARCHAR(255),
    color            VARCHAR(255),
    transponder_code BIGINT,
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE sighting
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    SMALLINT                                NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    point      BYTEA,
    moment     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sighting PRIMARY KEY (id)
);

CREATE TABLE trace
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version               SMALLINT                                NOT NULL,
    be_on_the_look_out_id BIGINT                                  NOT NULL,
    location              GEOMETRY(Point, 4326)                   NOT NULL,
    date                  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_trace PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE verification_token
(
    id          BIGINT NOT NULL,
    token       VARCHAR(255),
    app_user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_verificationtoken PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_username UNIQUE (username);

ALTER TABLE be_on_the_look_out
    ADD CONSTRAINT uc_beonthelookout_sku UNIQUE (sku);

ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_passwordresettoken_app_user UNIQUE (app_user_id);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verificationtoken_app_user UNIQUE (app_user_id);

ALTER TABLE bicycle
    ADD CONSTRAINT FK_BICYCLE_ON_ID FOREIGN KEY (id) REFERENCES be_on_the_look_out (id);

ALTER TABLE item
    ADD CONSTRAINT FK_ITEM_ON_ID FOREIGN KEY (id) REFERENCES be_on_the_look_out (id);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_ID FOREIGN KEY (id) REFERENCES be_on_the_look_out (id);

ALTER TABLE trace
    ADD CONSTRAINT FK_TRACE_ON_BEONTHELOOKOUT FOREIGN KEY (be_on_the_look_out_id) REFERENCES be_on_the_look_out (id);

ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFY_USER FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_VERIFY_USERvtk7Fw FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE be_on_the_look_out_photo
    ADD CONSTRAINT fk_be_on_the_look_out_photo_on_be_on_the_look_out FOREIGN KEY (be_on_the_look_out_id) REFERENCES bicycle (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_app_user FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (id);