name: Build and Deploy to Azure

on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: trackrejoicecontainerregistry.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t trackrejoicecontainerregistry.azurecr.io/trackrejoice:latest .
        docker push trackrejoicecontainerregistry.azurecr.io/trackrejoice:latest

    - name: Deploy to Azure Web App (Container)
      uses: azure/webapps-deploy@v2
      with:
        app-name: track-rejoice-webapp
        images: trackrejoicecontainerregistry.azurecr.io/trackrejoice:latest
