# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - track-rejoice

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://manoshelloworld.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d470fb5fb92f4dccbca694c779f70357 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a61f52e94d954c90a31f0fd1bf71fa20 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: manoshelloworld.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d470fb5fb92f4dccbca694c779f70357 }}/trackrejoice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'track-rejoice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4bca827ffe9c4402aa5cc2aca1ea1da0 }}
        images: 'manoshelloworld.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d470fb5fb92f4dccbca694c779f70357 }}/trackrejoice:${{ github.sha }}'